### ISSUE TITLE
Can you do better than `sleep()`?

### ISSUE THREAD

**Issue by cykusgdiv** [Moelf/Scryfall.jl#1]
https://github.com/Moelf/Scryfall.jl/blob/6d10b33be38ceff482dfa9a19ccfdb09dd472bc4/src/Scryfall.jl#L61

**Comment by Moelf** [comment]
Thx, this is per [Scryfall API Guildline](https://scryfall.com/docs/api) that:

> We kindly ask that you insert 50 – 100 milliseconds of delay between the requests you send to the server. (i.e., 10 requests per second on average).
